apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: team1

resources:
  - ../../manifests/llm-config
  - ../../manifests/tools/weather-tool
  - ../../manifests/agents/currency-converter

patches:
  - path: agent-endpoint-patch.yaml
