apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - llamastack-env.yaml

secretGenerator:
  - name: openai-secret
    envs:
      - openai.env

generatorOptions:
  disableNameSuffixHash: true
